apiVersion: v1
kind: Pod
metadata:
  name: busybox-test
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["sh", "-c", "echo 'Decrypted FOO from secret-vars.env:' && cat /etc/secrets/secret-vars.env && echo 'Decrypted Contents of secret-file.txt:' && cat /etc/secrets/secret-file.txt && sleep 3600"]
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secrets
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret
