apiVersion: v1
kind: Pod
metadata:
  name: busybox-test
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["sh", "-c", "echo 'FOO from secret-vars.env: && cat /etc/secrets/secret-vars.env' && echo 'Contents of secret-file.txt:' && cat /etc/secrets/secret-file.txt"]
    env:
      - name: FOO
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: FOO
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secrets
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret
