apiVersion: v1
kind: Pod
metadata:
  name: busybox-test
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["sh", "-c", "echo 'FOO from secret-vars.env: $FOO' && sleep 3600"]
    env:
      - name: FOO
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: FOO
