apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - generator.yaml

resources:
  - busybox.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated
configurations:
- name-reference.yaml
