apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-app

resources:
  - ../base
  - sops-secrets.yaml  # THÊM VÀO resources thay vì secretGenerator
  - sops-config.yaml

# XÓA secretGenerator section hoàn toàn
# XÓA patches section nếu không cần

labels:
  - pairs:
      environment: dev

images:
  - name: nginx
    newTag: alpine

replicas:
  - name: demo-app
    count: 2
