apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-app

resources:
  - ../base
  # XÓA - sops-secrets.yaml và - sops-config.yaml Ở ĐÂY

# THÊM secretGenerator để xử lý file đã mã hóa
secretGenerator:
  - name: app-secrets
    behavior: merge
    files:
      - sops-secrets.yaml
  - name: app-config
    behavior: merge
    files:
      - sops-config.yaml

labels:
  - pairs:
      environment: dev

images:
  - name: nginx
    newTag: alpine

replicas:
  - name: demo-app
    count: 2
