apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-app

resources:
  - ../base
  - sops-secrets.yaml
  - sops-config.yaml

labels:
  - pairs:
      environment: dev

images:
  - name: nginx
    newTag: alpine

replicas:
  - name: demo-app
    count: 2
