apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: demo-app
type: Opaque
data:
    database-url: ENC[AES256_GCM,data:wzLnqNlVDepi7P+TLpOePX1aLpasZ5S3NRcMYwt3keQ7qdKRwoAXmp21jkLEhV3Mqe+13ZKZNIXdRXVEqyIJ4A==,iv:aSTVmUpkPDvLEz5HN//OtN5hgNNdD21derh8d06A9Xs=,tag:53epsIwVyUp3Tum2esSN0Q==,type:str]
    api-key: ENC[AES256_GCM,data:3MGaCC+23UHuGpODyLiy6QrkCFaqQygM1g5sCvmat1s=,iv:mQ2IutuFqI5RcgODkt0aQ9ZecCIVQ9SUKBqNCADf7vA=,tag:9yZbgXpZJtlPKyLRYagGqw==,type:str]
stringData:
    config.json: ENC[AES256_GCM,data:npIdSVHYh8N+yAq7y5XlMOf0OF7Ob2R++iRmJ2nWiTa05/b3vX+KlNBg4cGIt+8LrKM7kSdEnNTPee6EQ6uvaRgn7JD8PQQT9NocIx2YC/ZZkPxumz3qKB0PWvKIyXPzFsW74yLNy0K+bGnbZDDaftefY47gNwZ0rmbteg4=,iv:x6Q3LzumCHkOFCvSpdxyYm7iiYv/kkIopvy1b+PXBcM=,tag:ooT6ubyTir15wFTCUwNeNQ==,type:str]
sops:
    lastmodified: "2025-08-30T14:22:01Z"
    mac: ENC[AES256_GCM,data:FiKL5I80XMFLO6FauY1MX4hkHQnN4rtIc9+0w6/r57NQPg+BZPHeznxW+/tXHMRcTa9CWv4vgu9x8/lzS5Vs/5YsQo0jCnpT7Og9YNpexBWJtY0KctZfnkarGwR52o9ejnMRBX4LUy+Wz24CLxBzEBXxeXpr+2wrwsx8ZjN5Roo=,iv:zbP61JgVOC8Gl0FIRybK6pXOKmDtpuJ00dElyRYmHqo=,tag:fwM/aDIgdJgkug3wFW0jHA==,type:str]
    pgp:
        - created_at: "2025-08-30T14:22:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA94vrtQPGQYHAQ/+MFNnx+oH3+PToLGFWwLM90unbltyDS8ipBl2k5tLkiN4
            S74ojCcE7zbLFkFYNuIIRQcMstvQZvOmrmW5Jan+cb20+NVuFzqAz76E/ZwDSzgc
            ndW0yevrgBtPkDC7dZDgHBz04VE6n9PosjPTvwmgh5XP9QvFOf+GuI21pFx1FVT2
            BoEH3OBO8ke6mI0pZvxXPeJ46Uckc8k4rlZ6kzP33CeoHh8F1SeZ2EkkmJsq+k4Z
            AkdZKN9rxdFuqs7mHqR0E4azC2fCgJIeIIfo9v7KWHefhVFs1YZTmWEWbhA19fj7
            mRNxCqqL6sAlI2cglqHFELokKYcarwNINFs39rR0DwW1gjCxgWxx+yAff+/bOrS7
            6NvZ25InnFta9jvphi88j5Nly72UlWbjESkrhpo4B9xVx5xcd/0RZHIfQucZfFkm
            WxDlsufC0+LqkLsJuF/iaNlq+ZyzdBs/O6ral5nC2UtTE3/I4yAi5tjw97PUtpNZ
            /9KoxbmcwLvfUcT614/PqItMvUIA8pR4GjXc+GXJVS6NGevsYYfshzTO9QUs8A3B
            cVU0d+g4ZjOTyodCTLjAb8a/fZx31iwT/AE0f8K+x7KE83t0NCLO4LpFijPGrnAh
            ALP5UiS3Hf0EAPrQYBzAJpoeTggfOxg4Li9kiQcurVxpLkD3UNhtcTR6SMQANQ7S
            XgEiIZwdDO0oXe5Xe5Lb0kRjV3uwS20QCH9LHRIsnSSwavUKgNJE7t3TVaBzvORc
            uazDrg4ZVmjSmo+WszZHj60jQjcz27M9SWlYzlqU05slWQb4sXO3ghLyQysC2j8=
            =qsLg
            -----END PGP MESSAGE-----
          fp: 0258C3662CDA05AB59DE88EFEC4B3E036E6CE741
    encrypted_regex: ^(data|stringData|apiKey|password|token|secret|credential)$
    version: 3.10.2
