apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-app

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml

# THAY commonLabels BẰNG labels
labels:
  - pairs:
      app: demo-app
      environment: base
